config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence:true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  validates :title, presence:true
  validates :body, presence:true
  validates :email, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :text)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.create(post_params)
    @post.secret_key = rand(1000..9999)

    p @post

    if @post.save
      flash.notice = "your secret key is #{@post.secret_key} . You will need this number to edit or delete the post"
      redirect_to category_post_path(@category, @post)
    else
      render 'new'
    end

  end

  def show
    p flash.notice
    @post = Post.find(params[:id])
    @category = @post.category
  end

  def index
    @category = Category.find(params[:category_id])
    redirect_to @category
  end

  def edit
    @post = Post.find(params[:id])
    @category = @post.category
  end

  def update
    @post = Post.find(params[:id])
    @category = @post.category

    if @post.secret_key == post_params[:secret_key] && @post.update(post_params)
      redirect_to category_post_path(@category, @post)
    else
      render 'edit'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :price, :email, :body, :location, :secret_key)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>Craigslist Jr.</h1>

<h3>Categories</h3>
<ul>
<% @categories.each do |category| %>
<li>
  <%= link_to category.name, category_path(category) %>
</li>
<% end %>

</ul>

<%= link_to 'New Category', new_category_path%>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for :category, url: categories_path do |f| %>
  <p>
    <%= f.label :name%> <br />
    <%= f.text_field :name%> <br />
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>

<% @posts.each do |post| %>
  <li>
    <%= link_to post.title, category_post_path(@category, post) %>
  </li>
<% end %>
</ul>

<%= link_to 'New Post', new_category_post_path(@category) %> <br />
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigslistRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash.notice %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>edit</h2>
<%= form_for :post, url: category_post_path(@category, @post), method: :patch do |f| %>
  <% if @post %>
    <% if @post.errors.any? %>
      <div id='new_post_errors'>
        <h2>
          <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved :
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li>
              <%= msg%>
            </li>
          <% end %>
        </ul>
    <% end %>
  <% end %>
  <p>
    <%= f.label :secret_key %>* <br />
    <%= f.text_field :secret_key%> <br />
  </p>
  <p>
    <%= f.label :title %>* <br />
    <%= f.text_field :title%> <br />
  </p>
  <p>
    <%= f.label :price%> <br />
    <%= f.text_field :price%> <br />
  </p>
  <p>
    <%= f.label :email%>* <br />
    <%= f.text_field :email%> <br />
  </p>
  <p>
    <%= f.label :body%>* <br />
    <%= f.text_area :body%> <br />
  </p>
  <p>
    <%= f.label :location%> <br />
    <%= f.text_field :location%> <br />
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

<p>
  * = required
</p>

app/views/posts/new.html.erb
<h1>New Post in <%=@category.name %></h1>

<%= form_for([@category, @category.posts.build]) do |f| %>
  <% if @post %>
    <% if @post.errors.any? %>
      <div id='new_post_errors'>
        <h2>
          <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved :
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li>
              <%= msg%>
            </li>
          <% end %>
        </ul>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %>* <br />
    <%= f.text_field :title%> <br />
  </p>
  <p>
    <%= f.label :price%> <br />
    <%= f.text_field :price%> <br />
  </p>
  <p>
    <%= f.label :email%>* <br />
    <%= f.text_field :email%> <br />
  </p>
  <p>
    <%= f.label :body%>* <br />
    <%= f.text_area :body%> <br />
  </p>
  <p>
    <%= f.label :location%> <br />
    <%= f.text_field :location%> <br />
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

<p>
  * = required
</p>

app/views/posts/show.html.erb
<h1><%= @post.title %> - <%=@post.price %></h1>
  <p>
    <%= @post.body %>
  </p>
  <p>
    <%= @post.location %>
  </p>

  <%= link_to "back to #{@category.name}", category_path(@category) %>

  <%= link_to 'edit or delete', edit_category_post_path(@category, @post) %>